
name: Build kernel arch packages
on:
  push:
    tags:
      - 'arch*'
env:
  GPG_KEY_ID: 56C464BAAC421453

jobs:
  build:
    name: Build Linux kernel package
    runs-on: ubuntu-latest
    container: archlinux

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        # Install makepkg deps
        pacman --noconfirm -Syu
        pacman --noconfirm -S sudo binutils fakeroot base-devel git   \
                              xmlto docbook-xsl kmod inetutils bc dtc \
                              aarch64-linux-gnu-gcc aarch64-linux-gnu-glibc
        # Fix permissions (can't makepkg as root)
        echo "nobody ALL=(ALL) NOPASSWD: /usr/bin/pacman" >> /etc/sudoers
    - name: Set up makepkg-aarch64 for cross-compilation
      run: |
        cd makepkg-aarch64
        # Fix permissions (can't makepkg as root)
        chown -R nobody .
        # Build and install 
        su nobody --pty -p -s /bin/bash -c 'makepkg -fi --syncdeps --skippgpcheck --noconfirm'
    - name: Build Package
      run: |
        cd linux-surface
        # Fix permissions (can't makepkg as root)
        chown -R nobody .
        # Package compression settings (Matches latest Arch)
        export PKGEXT='.pkg.tar.zst'
        export COMPRESSZST=(zstd -c -T0 --ultra -20 -)
        export MAKEFLAGS="-j2"
        # Build
        su nobody --pty -p -s /bin/bash -c 'makepkg-aarch64 -f --syncdeps --skippgpcheck --noconfirm'
    - name: Prepare release
      run: |
        mkdir release
        mv linux-surface/*.pkg.tar.zst release
    - name: Sign packages
      env:
        GPG_KEY: ${{ secrets.LINUX_SURFACE_GPG_KEY }}
      run: |
        cd release
        # import GPG key
        echo "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes
        export GPG_TTY=$(tty)
        # sign packages
        ls *.pkg.tar.zst | xargs -L1 gpg --detach-sign --batch --no-tty -u $GPG_KEY_ID
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: linux-surface-aarch64-latest
        path: release
  
  release:
    name: Publish release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: linux-surface-aarch64-latest

    - name: Upload assets
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.LINUX_SURFACE_BOT_TOKEN }}
        file: ./*-latest/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
